### ISSUE TITLE
cloud.png

### ISSUE THREAD

**Issue by robotCurry** [stepfencurryxiao/Cross-Fire#5]
can not open the "cloud.png"

**Comment by stepfencurryxiao** [comment]
Done.[here](https://github.com/stepfencurryxiao/Cross-Fire/blob/master/image/cloud.png)

**Comment by stepfencurryxiao** [comment]
Done.[here](https://github.com/stepfencurryxiao/Cross-Fire/blob/master/image/cloud.png)
