### ISSUE TITLE
About life

### ISSUE THREAD

**Issue by robotCurry** [stepfencurryxiao/Cross-Fire#8]
Can you set more life?

**Comment by stepfencurryxiao** [comment]
Ok,I will try a different way to solve this problem,even my code.Feel free can create a pull request😀

**Comment by stepfencurryxiao** [comment]
I find a very big bug in my game,I set 3 Life but as soon as it meets enemy planes, it dies.I will continue to fix this bug.

**Comment by robotCurry** [comment]
Can you show me the code?

**Comment by robotCurry** [comment]
If you need help,I can pull a request.

**Comment by stepfencurryxiao** [comment]
You don't need pull a request,I think that I can solve it by myself.😀 @robotCurry

**Comment by stepfencurryxiao** [comment]
Solved,Look this [request](https://github.com/stepfencurryxiao/Cross-Fire/pull/9)
